volumes:
  kubearmor-init-vol:
    name: kubearmor-init-vol
  {{- if .SpireEnabled }}
  spire-vol:
    name: spire-vol
  {{- end }}

services:

  {{- if .SpireEnabled }}
  spire-agent:
    profiles:
      - "spire-agent"
    container_name: spire-agent
    image: {{.SPIREAgentImage}}
    pull_policy: "{{.ImagePullPolicy}}"
    command:
      - "-config"
      - "/etc/spire/conf/agent.conf"
      - "-expandEnv"
    volumes:
      # for SPIRE config
      - "{{.ConfigPath}}:/etc"
      # for SVID persistence
      - "spire-vol:/opt/spire-agent/spire-data:rw"
      # for SPIRE socket
      - "/var/run/:/var/run/"
      # for spire SVID persistence
      # TODO: this is not consumed right now due to user perms
      - "/var/lib/spire/agent:/var/lib/spire/agent"
    labels:
      app: spire-agent
    networks:
      accuknox-net:
        aliases:
          - spire-agent
    restart: always
    ports:
      - "9091:9091"
      - "9090:9090"
    pid: "host"
    privileged: true

  wait-for-it:
    container_name: wait-for-it
    profiles:
      - "accuknox-agents"
    depends_on:
      spire-agent:
        condition: service_started
    image: {{.WaitForItImage}}
    pull_policy: "{{.ImagePullPolicy}}"
    command: ["-t", "60", "spire-agent:9090"]
    labels:
      app: wait-for-it
    networks:
      accuknox-net:
        aliases:
          - wait-for-it
  {{- end }}
  kubearmor-init:
    profiles:
      - "kubearmor-only"
      - "kubearmor"
    container_name: kubearmor-init
    image: {{.KubeArmorInitImage}}
    pull_policy: "{{.ImagePullPolicy}}"
    user: root
    labels:
      app: kubearmor-init
    volumes:
      - "kubearmor-init-vol:/opt/kubearmor/BPF:rw"
      - "/lib/modules:/lib/modules:ro"
      - "/sys/fs/bpf:/sys/fs/bpf:ro"
      - "/sys/kernel/security:/sys/kernel/security:ro"
      - "/sys/kernel/debug:/sys/kernel/debug:ro"
      - "/media/root/etc/os-release:/media/root/etc/os-release:ro"
    restart: on-failure
    privileged: true
    networks:
      accuknox-net:
        aliases:
          - kubearmor-init

  kubearmor:
    profiles:
      - "kubearmor-only"
      - "kubearmor"
    depends_on:
      kubearmor-init:
        condition: service_completed_successfully
    hostname: {{.Hostname}}
    container_name: kubearmor
    image: "{{.KubeArmorImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    command:
      - "-k8s=false"
      - "-enableKubeArmorPolicy"
      - "-enableKubeArmorHostPolicy"
      - "-visibility={{.KubeArmorVisibility}}"
      - "-hostVisibility={{.KubeArmorHostVisibility}}"
      - "-criSocket=unix:///var/run/docker.sock"
      - "-enableKubeArmorStateAgent"
      - "-defaultFilePosture={{.KubeArmorFilePosture}}"
      - "-defaultNetworkPosture={{.KubeArmorNetworkPosture}}"
      - "-defaultCapabilitiesPosture={{.KubeArmorCapPosture}}"
      - "-hostDefaultFilePosture={{.KubeArmorHostFilePosture}}"
      - "-hostDefaultNetworkPosture={{.KubeArmorHostNetworkPosture}}"
      - "-hostDefaultCapabilitiesPosture={{.KubeArmorHostCapPosture}}"
      - "-alertThrottling={{.KubeArmorAlertThrottling}}"
      - "-maxAlertPerSec={{.KubeArmorMaxAlertsPerSec}}"
      - "-throttleSec={{.KubeArmorThrottleSec}}"
    labels:
      app: kubearmor
    volumes:
      - "kubearmor-init-vol:/opt/kubearmor/BPF"
      - "/sys/fs/bpf:/sys/fs/bpf"
      - "/sys/kernel/security:/sys/kernel/security"
      - "/sys/kernel/debug:/sys/kernel/debug"
      - "/etc/apparmor.d:/etc/apparmor.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/run/docker:/run/docker"
      - "/var/lib/docker:/var/lib/docker"
    restart: always
    ports:
      - "{{.KubeArmorPort}}:32767"
    networks:
      accuknox-net:
        aliases:
          - kubearmor
    pid: "host"
    privileged: true

  kubearmor-vm-adapter:
    profiles:
      - "kubearmor-only"
      - "kubearmor"
    depends_on:
      {{- if .SpireEnabled }}
      wait-for-it:
        condition: service_completed_successfully
      {{- end }}
      kubearmor:
        condition: service_started
    container_name: kubearmor-vm-adapter
    image: "{{.KubeArmorVMAdapterImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    environment:
    - "test=true"
    {{- if .ProxyEnabled  }}
    - "JOIN_TOKEN={{.JoinToken}}"
    {{- end }}
    {{- range .ProxyExtraArgs }}
    - {{ . }}
    {{- end }}
    command:
      - "--kubearmor-addr={{.KubeArmorURL}}"
      - "--relay-server-addr={{.RelayServerURL}}"
      {{- if trimPrefix "v" .ReleaseVersion | semverCompare ">0.9.1" }}
      - "--node-state-refresh={{.NodeStateRefreshTime}}"
      {{- end }}
      {{- if .SpireEnabled }}
      - "--spire"
      - "--spire-agent=unix:///var/run/spire/agent.sock"
      - "--spire-cert={{.SpireCert}}"
      {{- end }}
      {{- if .TlsEnabled }}
      - "--tls"
      - "--policy-topic={{.PoliciesTopic}}"
      - "--state-topic={{.StateEventTopic}}"
      - "--alert-topic={{.AlertsTopic}}"
      - "--logs-topic={{.LogsTopic}}"
      - "--kmux-config-policies=/opt/kubearmor-vm-adapter/{{.PoliciesKmuxConfig}}"
      - "--kmux-config-state=/opt/kubearmor-vm-adapter/{{.StateKmuxConfig}}"
      - "--kmux-config-alerts=/opt/kubearmor-vm-adapter/{{.AlertsKmuxConfig}}"
      - "--kmux-config-logs=/opt/kubearmor-vm-adapter/{{.LogsKmuxConfig}}"
      {{- if .ProxyEnabled }}
      - "--annotation-topic={{.AnnotationTopic}}"
      - "kmux-config-annotation=/opt/kubearmor-vm-adapter/{{.AnnotationKmuxConfig}}"
      {{- end }}
      {{- else }}
      - "--sia-addr={{.SIAAddr}}"
      - "--pea-addr={{.PEAAddr}}"
      - "--harden-addr={{.HardenAddr}}"
      {{- end }}
    volumes:
      - "{{.ConfigPath}}:/opt"
      {{- if .SpireEnabled }}
      # for spire socket
      - "/var/run:/var/run:ro"
      {{- end }}
    labels:
      app: kubearmor-vm-adapter
    restart: always
    network_mode: "host"

  summary-engine:
    profiles:
      - "accuknox-agents"
    depends_on:
      {{- if .SpireEnabled }}
      wait-for-it:
        condition: service_completed_successfully
      {{- end }}
      kubearmor-vm-adapter:
        condition: service_started
    container_name: summary-engine
    image: "{{.SumEngineImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    command: ["--config", "/opt/sumengine/config.yaml", "--kmux-config", "/opt/sumengine/kmux-config.yaml"]
    labels:
      app: sumengine
    environment:
    - "test=true"
    {{- if .ProxyEnabled  }}
    - "JOIN_TOKEN={{.JoinToken}}"
    {{- end }}
    {{- range .ProxyExtraArgs }}
    - {{ . }}
    {{- end }}
    volumes:
      - "{{.ConfigPath}}:/opt"
      {{- if .SpireEnabled }}
      # for spire socket
      - "/var/run:/var/run:ro"
      {{- end }}
    restart: always
    pid: "host"
    network_mode: "host"

networks:
  accuknox-net:
    name: accuknox-net
    ipam:
      config:
        - subnet: {{.NetworkCIDR}}
