version: '3.8'

volumes:
  spire-vol:
    name: spire-vol
  kubearmor-init-vol:
    name: kubearmor-init-vol

services:
  spire-agent:
    profiles:
      - "spire-agent"
    container_name: spire-agent
    image: {{.SPIREAgentImage}}
    pull_policy: "{{.ImagePullPolicy}}"
    command:
      - "-config"
      - "/etc/spire/conf/agent.conf"
      - "-expandEnv"
    volumes:
      # for SPIRE config
      - "{{.ConfigPath}}:/etc"
      # for SVID persistence
      - "spire-vol:/opt/spire-agent/spire-data:rw"
      # for SPIRE socket
      - "/var/run/:/var/run/"
      # for spire SVID persistence
      # TODO: this is not consumed right now due to user perms
      - "/var/lib/spire/agent:/var/lib/spire/agent"
    labels:
      app: spire-agent
    networks:
      accuknox-net:
        aliases:
          - spire-agent
    restart: always
    ports:
      - "9091:9091"
      - "9090:9090"
    pid: "host"
    privileged: true

  wait-for-it:
    container_name: wait-for-it
    profiles:
      - "accuknox-agents"
    depends_on:
      spire-agent:
        condition: service_started
    image: {{.WaitForItImage}}
    pull_policy: "{{.ImagePullPolicy}}"
    command: ["-t", "60", "spire-agent:9090"]
    labels:
      app: wait-for-it
    networks:
      accuknox-net:
        aliases:
          - wait-for-it

  kubearmor-init:
    profiles:
      - "kubearmor-only"
      - "kubearmor"
    container_name: kubearmor-init
    image: {{.KubeArmorInitImage}}
    pull_policy: "{{.ImagePullPolicy}}"
    user: root
    labels:
      app: kubearmor-init
    volumes:
      - "kubearmor-init-vol:/opt/kubearmor/BPF:rw"
      - "/lib/modules:/lib/modules:ro"
      - "/sys/fs/bpf:/sys/fs/bpf:ro"
      - "/sys/kernel/security:/sys/kernel/security:ro"
      - "/sys/kernel/debug:/sys/kernel/debug:ro"
      - "/media/root/etc/os-release:/media/root/etc/os-release:ro"
    restart: on-failure
    privileged: true
    networks:
      accuknox-net:
        aliases:
          - kubearmor-init

  kubearmor:
    profiles:
      - "kubearmor-only"
      - "kubearmor"
    depends_on:
      kubearmor-init:
        condition: service_completed_successfully
    hostname: {{.Hostname}}
    container_name: kubearmor
    image: "{{.KubeArmorImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    command:
      - "-k8s=false"
      - "-enableKubeArmorPolicy"
      - "-enableKubeArmorHostPolicy"
      - "-visibility={{.KubeArmorVisibility}}"
      - "-hostVisibility={{.KubeArmorHostVisibility}}"
      - "-criSocket=unix:///var/run/docker.sock"
      - "-enableKubeArmorStateAgent"
      - "-defaultFilePosture={{.KubeArmorFilePosture}}"
      - "-defaultNetworkPosture={{.KubeArmorNetworkPosture}}"
      - "-defaultCapabilitiesPosture={{.KubeArmorCapPosture}}"
      - "-hostDefaultFilePosture={{.KubeArmorHostFilePosture}}"
      - "-hostDefaultNetworkPosture={{.KubeArmorHostNetworkPosture}}"
      - "-hostDefaultCapabilitiesPosture={{.KubeArmorHostCapPosture}}"
      - "-alertThrottling={{.KubeArmorAlertThrottling}}"
      - "-maxAlertPerSec={{.KubeArmorMaxAlertsPerSec}}"
      - "-throttleSec={{.KubeArmorThrottleSec}}"
    labels:
      app: kubearmor
    volumes:
      - "kubearmor-init-vol:/opt/kubearmor/BPF"
      - "/sys/fs/bpf:/sys/fs/bpf"
      - "/sys/kernel/security:/sys/kernel/security"
      - "/sys/kernel/debug:/sys/kernel/debug"
      - "/etc/apparmor.d:/etc/apparmor.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/run/docker:/run/docker"
      - "/var/lib/docker:/var/lib/docker"
    restart: always
    ports:
      - "{{.KubeArmorPort}}:32767"
    networks:
      accuknox-net:
        aliases:
          - kubearmor
    pid: "host"
    privileged: true

  kubearmor-relay-server:
    profiles:
      - "accuknox-agents"
    depends_on:
      - kubearmor
    container_name: kubearmor-relay-server
    image: "{{.KubeArmorRelayServerImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    command:
      - "-enableReverseLogClient"
      - "-gRPCPort=32768"
    volumes:
      - "{{.ConfigPath}}:/opt"
    restart: always
    labels:
      app: kubearmor-relay-server
    ports:
      - "32768:32768"
    networks:
      accuknox-net:
        aliases:
          - kubearmor-relay-server

  kubearmor-vm-adapter:
    profiles:
      - "kubearmor-only"
      - "kubearmor"
    depends_on:
      kubearmor:
        condition: service_started
      summary-engine:
        condition: service_started
      discover:
        condition: service_started
      {{- if .TlsEnabled }}
      shared-informer-agent:
        condition: service_started
      policy-enforcement-agent:
        condition: service_started
      {{- end }}
    container_name: kubearmor-vm-adapter
    image: "{{.KubeArmorVMAdapterImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    command:
      - "--kubearmor-addr={{.KubeArmorURL}}"
      {{- if .TlsEnabled }}
      - "--tls"
      - "--policy-topic={{.PoliciesTopic}}"
      - "--state-topic={{.StateEventTopic}}"
      - "--alert-topic={{.AlertsTopic}}"
      - "--logs-topic={{.LogsTopic}}"
      - "--kmux-config-policies=/opt/vm-adapter/{{.PoliciesKmuxConfig}}"
      - "--kmux-config-state=/opt/vm-adapter/{{.StateKmuxConfig}}"
      - "--kmux-config-alerts=/opt/vm-adapter/{{.AlertsKmuxConfig}}"
      - "--kmux-config-logs=/opt/vm-adapter/{{.LogsKmuxConfig}}"
      {{- else }}
      - "--relay-server-addr={{.RelayServerURL}}"
      - "--sia-addr={{.SIAAddr}}"
      - "--pea-addr={{.PEAAddr}}"
      - "--harden-addr={{.HardenAddr}}"
      {{- end }}
    labels:
      app: kubearmor-vm-adapter
    restart: always
    volumes:
      - "{{.ConfigPath}}:/opt"
    networks:
      accuknox-net:
        aliases:
          - kubearmor-vm-adapter

  shared-informer-agent:
    profiles:
      - "accuknox-agents"
    depends_on:
      wait-for-it:
        condition: service_completed_successfully
      kubearmor:
        condition: service_started
      {{- if not .TlsEnabled }}
      kubearmor-vm-adapter:
        condition: service_started
      {{- end }}
    container_name: shared-informer-agent
    image: "{{.SIAImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    command: ["-config-path", "/opt/sia/"]
    labels:
      app: shared-informer-agent
    volumes:
      - "{{.ConfigPath}}:/opt"
      - "/var/run:/var/run:ro"
    restart: always
    pid: "host"
    ports:
      - "32769:32769"
    networks:
      accuknox-net:
        aliases:
          - shared-informer-agent

  feeder-service:
    profiles:
      - "accuknox-agents"
    depends_on:
      wait-for-it:
        condition: service_completed_successfully
      kubearmor-relay-server:
        condition: service_started
      summary-engine:
        condition: service_started
      discover:
        condition: service_started
      {{- if not .TlsEnabled }}
      hardening-agent:
        condition: service_started
      {{- end }}
    container_name: feeder-service
    image: "{{.FeederImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    labels:
      app: feeder-service
    volumes:
      - "{{.ConfigPath}}:/opt"
      - "/var/run:/var/run:ro"
    restart: always
    environment:
      - "ENABLE_VM=true"
      - "CLUSTER_NAME=default"
      - "HUBBLE_ENABLED=false"
      - "KAFKA_ENABLED=false"
      - "DISCOVERYENGINE_ENABLED=true"
      - "DISCOVERYENGINE_VERSION=2"

      - "KUBEARMOR_ENABLED=true"
      - "KUBEARMOR_URL={{.RelayServerAddr}}"
      - "KUBEARMOR_PORT={{.RelayServerPort}}"

      - "KMUX_LOGS_ENABLED={{.EnableLogs}}"
      - "KMUX_CONFIG_PATH={{.KmuxConfigPath}}"

      - "IGNORE_SUMMARY_EVENTS=Network:AF_UNIX,AF_NETLINK"

      - "SPIRE_AGENT_URL=unix:///var/run/spire/agent.sock"
      - "SPIRE_ENABLED=true"
      - "TLS_ENABLED=true"
      - "TLS_CERT_FILE=/opt/cert/encoded.pem"
      - "RABBITMQ_ENABLED=true"
      - "RABBITMQ_ALERTS_TOPIC={{.AlertsTopic}}"
      - "RABBITMQ_LOGS_TOPIC={{.LogsTopic}}"
      - "POLICY_TOPIC={{.PolicyV1Topic}}"
      - "SUMMARY_TOPIC={{.SummaryV2Topic}}"
      - DEPLOY_MODE="vm"
      - "RABBITMQ_ALERTS_KMUX_CONFIG=/opt/feeder-service/{{.AlertsKmuxConfig}}"
      - "RABBITMQ_LOGS_KMUX_CONFIG=/opt/feeder-service/{{.LogsKmuxConfig}}"
      - "DISCOVERYENGINE_POLICY_ENABLED=true"
      - "KMUX_CONFIG_POLICY=/opt/feeder-service/{{.PolicyKmuxConfig}}"
      - "KMUX_CONFIG_SUMMARY=/opt/feeder-service/{{.SummaryKmuxConfig}}"

    pid: "host"
    networks:
      accuknox-net:
        aliases:
          - feeder-service

  policy-enforcement-agent:
    profiles:
      - "accuknox-agents"
    depends_on:
      wait-for-it:
        condition: service_completed_successfully
      kubearmor-relay-server:
        condition: service_started
    container_name: policy-enforcement-agent
    image: "{{.PEAImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    command: ["-config-path", "/opt/pea/"]
    labels:
      app: policy-enforcement-agent
    volumes:
      - "{{.ConfigPath}}:/opt"
      # for spire socket
      - "/var/run:/var/run:ro"
    restart: always
    ports:
      - "32770:32770"
    pid: "host"
    networks:
      accuknox-net:
        aliases:
          - policy-enforcement-agent
  discover:
    profiles:
      - "accuknox-agents"
    depends_on:
      {{- if .DeployRMQ }}
      rabbitmq:
        condition: service_started
      {{- end }}
      summary-engine:
        condition: service_started
    container_name: discover
    image: "{{.DiscoverImage}}"
    environment:
      "ENABLE_GRPC": 'false'
    pull_policy: "{{.ImagePullPolicy}}"
    command: ["--config", "/opt/discover/config.yaml", "--kmux-config", "/opt/discover/kmux-config.yaml"]
    labels:
      app: discover
    volumes:
      - "{{.ConfigPath}}:/opt"
    restart: always
    pid: "host"
    networks:
      accuknox-net:
        aliases:
          - discover
  summary-engine:
    profiles:
      - "accuknox-agents"
    depends_on:
      {{- if .DeployRMQ }}
      rabbitmq:
        condition: service_started
      {{- end }}
      kubearmor-relay-server:
        condition: service_started
    container_name: summary-engine
    image: "{{.SumEngineImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    command: ["--config", "/opt/sumengine/config.yaml", "--kmux-config", "/opt/sumengine/kmux-config.yaml"]
    labels:
      app: sumengine
    volumes:
      - "{{.ConfigPath}}:/opt"
    restart: always
    pid: "host"
    networks:
      accuknox-net:
        aliases:
          - sumengine
  hardening-agent:
    profiles:
      - "accuknox-agents"
    depends_on:
      {{- if .DeployRMQ }}
      rabbitmq:
        condition: service_started
      {{- end }}
      kubearmor-relay-server:
        condition: service_started
    container_name: hardening-agent
    image: "{{.HardeningAgentImage}}"
    pull_policy: "{{.ImagePullPolicy}}"
    command: ["start", "--config", "/opt/hardening-agent/config.yaml", "--kmux-config", "/opt/hardening-agent/kmux-config.yaml"]
    labels:
      app: hardening-agent
    volumes:
      - "{{.ConfigPath}}:/opt"
    restart: always
    ports:
      - "32771:32771"
    pid: "host"
    networks:
      accuknox-net:
        aliases:
          - hardening-agent

  {{- if .DeployRMQ }}
  rabbitmq:
    image: {{.RMQImage}}
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "5671:5671"
      - "15672:15672"
    restart: always
    pid: "host"  
    networks:
      accuknox-net:
        aliases:
          - rabbitmq
    volumes:
      - "{{.ConfigPath}}/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "{{.ConfigPath}}/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"
      - "{{.ConfigPath}}/rabbitmq/ca_certificate.pem:/etc/ssl/ca_certificate.pem"
      - "{{.ConfigPath}}/rabbitmq/certificate.pem:/etc/ssl/server_certificate.pem"
      - "{{.ConfigPath}}/rabbitmq/key.pem:/etc/ssl/server_key.pem"
  {{- end }}

networks:
  accuknox-net:
    name: accuknox-net
    ipam:
      config:
        - subnet: {{.NetworkCIDR}}
