server:
  port: :6060
  basepath: /pea

application:
  name: policy-enf-agent

spire:
  {{ if .ProxyEnabled }}
  enable: false
  {{ else }}
  enable: true
  {{ end }}
  agent: "unix:///var/run/spire/agent.sock"

endpoint:
  urlendpoint: /pps/api/v1/policy-provider/fetch-policy
  baseurlendpoint: https://{{.PPSHost}}

statusendpoint:
  endpoint: https://{{.PPSHost}}/pps/api/v1/policy-provider/change-status-policy

syncuptime:
  t: 5

kmux-config-file: {{.KmuxConfigPath}}

annotation:
  statusendpoint: /pps/api/v1/policy-provider/update-annotation-status
  annotationendpoint: /pps/api/v1/policy-provider/fetch-annotations
  basepath: https://{{.PPSHost}}

non-k8s:
  enable: true
  policy-server-port: 32770
tls:
  enabled: {{.TlsEnabled}}
  policy:
    topic: {{.PoliciesTopic}}
    kmux-config: {{.PoliciesKmuxConfig}}
  state:
    topic: {{.StateEventTopic}}
    kmux-config: {{.StateKmuxConfig}}

policy-watcher:
  enable: false

deployMode: "vm"

reconciler:
  enable: true
  interval: 30m

log-level: info

proxy:
  enabled: {{.ProxyEnabled}}
  address: {{.ProxySaaSAddr}}

connect-rpc:
  enabled: true
  address: https://{{.PPSHost}}