name: Build knoxctl

on:
  push:
    branches:
      - '*'

jobs:

  build-knoxctl:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: AccuKnox Runtime Monitoring
        uses: accuknox/report-action@v0.3.3
        with:
          knoxctl_version: '0.6.1'

      - uses: actions/setup-go@v2
        with:
          go-version: "v1.21"

      - name: Setup GH Token
        env:
          GOPRIVATE: github.com/accuknox/*
          USER: accuknox-user
          TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Build knoxctl
        run: make
