name: PR Checks

on:
  pull_request_target:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:

  go-checks:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: AccuKnox Runtime Monitoring
        uses: accuknox/report-action@v0.3.15
        with:
          knoxctl_version: '0.6.2'
          kubearmor_version: '1.3.8'

      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Setup GH Token
        env:
          GOPRIVATE: github.com/accuknox/*
          USER: ${{ secrets.AK_USER }}
          TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
          go env -w GOPRIVATE=github.com/accuknox

      - name: Check gofmt
        run: make gofmt

      - name: Run Gosec Security Scanner
        run: make gosec

      - name: Build knoxctl
        run: make

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: AccuKnox Runtime Monitoring
        uses: accuknox/report-action@v0.3.2

      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Setup GH Token
        env:
          GOPRIVATE: github.com/accuknox/*
          USER: ${{ secrets.AK_USER }}
          TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
          go env -w GOPRIVATE=github.com/accuknox

      - name: Run unit tests
        run: make test
