name: Release knoxctl

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  knoxctl-release:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/accuknox/
      GH_ACCESS_TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
      GIT_KEY: ${{ secrets.GIT_KEY }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Setup access for private go modules
        env:
          GOPRIVATE: github.com/accuknox/*
          USER: accuknox-user
          TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Tag Name
        id: get_tag
        run: echo "::set-output name=TAG_NAME::$(git describe --tags --abbrev=0)"

      # create release in knoxctl-website repo
      - name: Create release of knoxctl-website repo
        # recommended action by GitHub actions/create-release after archive
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ steps.get_tag.outputs.tag }}"
          body: "Release ${{ steps.get_tag.outputs.TAG_NAME }} for knoxctl a.k.a accuknox-cli."
          repository: accuknox/knoxctl-website
          token: ${{ secrets.AK_PAT_REPO_SCOPE }}
          make_latest: true
          files: |
            dist/*.tar.gz
            dist/*.txt
            dist/*.cert
            dist/*.sig
